#!/usr/bin/env python3
"""生成控制台的配色令牌：`res/console/tokens.css` 里 @generated 之间的那一段。

颜色不手调。种子色经 Material Color Utilities 的 HCT 算法（2025 版规范，
Tonal Spot 变体）推出全部系统角色，浅色、深色各一套，另各加一套「提高对比度」
（contrast_level 0.5，供 `prefers-contrast: more`，即 Apple 的「增强对比度」
与 Windows 的对比度主题之外的浏览器偏好）。

M3 只有 error 一种语义色；日志与连接状态还要「成功」「警告」。这两支按 M3 的
自定义色做法：先向种子色相做 harmonize，再用同一套 Tonal Spot 规则取
primary / on-primary / primary-container / on-primary-container 四个角色，
于是它们与主色在明度结构上完全同构，对比度也由算法保证。

同一次运行还把 theme-color 同步写进 index.html 与 manifest，避免两处漂移。

依赖：pip install materialyoucolor
运行：python3 scripts/make-tokens.py [--check]
"""

import json
import re
import sys
from pathlib import Path

from materialyoucolor.blend import Blend
from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors as M
from materialyoucolor.hct.hct import Hct
from materialyoucolor.scheme.scheme_tonal_spot import SchemeTonalSpot

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "res/console/tokens.css"
INDEX = ROOT / "res/console/index.html"
MANIFEST = ROOT / "res/console/manifest.webmanifest"

# 种子：靛青。知微是「看见细处」，取书写与夜读的颜色，而不是告警式的高饱和蓝。
SEED = 0xFF3F51B5
# 自定义语义色的原始色相，harmonize 之后才用。
SUCCESS = 0xFF2E8B57
WARNING = 0xFFB8860B

ROLES = [
    "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
    "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
    "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
    "error", "onError", "errorContainer", "onErrorContainer",
    "surface", "surfaceDim", "surfaceBright",
    "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
    "surfaceContainerHigh", "surfaceContainerHighest",
    "onSurface", "onSurfaceVariant", "outline", "outlineVariant",
    "inverseSurface", "inverseOnSurface", "inversePrimary",
    "scrim", "shadow",
]


def kebab(name: str) -> str:
    return re.sub(r"([A-Z])", lambda m: "-" + m.group(1).lower(), name)


def hexs(argb: int) -> str:
    return "#%06x" % (argb & 0xFFFFFF)


def scheme(source: int, dark: bool, contrast: float):
    return SchemeTonalSpot(Hct.from_int(source), dark, contrast, spec_version="2025")


def block(dark: bool, contrast: float) -> list[str]:
    base = scheme(SEED, dark, contrast)
    lines = [f"  --md-sys-color-{kebab(role)}: {hexs(getattr(M, role).get_argb(base))};" for role in ROLES]
    for name, raw in (("success", SUCCESS), ("warning", WARNING)):
        custom = scheme(Blend.harmonize(raw, SEED), dark, contrast)
        for role, suffix in (
            ("primary", ""),
            ("onPrimary", "on-"),
            ("primaryContainer", "container"),
            ("onPrimaryContainer", "on-container"),
        ):
            key = {"": name, "on-": f"on-{name}", "container": f"{name}-container",
                   "on-container": f"on-{name}-container"}[suffix]
            lines.append(f"  --md-sys-color-{key}: {hexs(getattr(M, role).get_argb(custom))};")
    return lines


def generated() -> tuple[str, dict]:
    light, dark = block(False, 0.0), block(True, 0.0)
    light_hc, dark_hc = block(False, 0.5), block(True, 0.5)
    out = [
        "/* @generated by scripts/make-tokens.py — 不要手改这一段 */",
        f"/* seed {hexs(SEED)} · Tonal Spot · spec 2025 */",
        ":root {",
        "  color-scheme: light;",
        *light,
        "}",
        "@media (prefers-color-scheme: dark) {",
        "  :root {",
        "    color-scheme: dark;",
        *["  " + line for line in dark],
        "  }",
        "}",
        "@media (prefers-contrast: more) {",
        "  :root {",
        *["  " + line for line in light_hc],
        "  }",
        "}",
        "@media (prefers-contrast: more) and (prefers-color-scheme: dark) {",
        "  :root {",
        *["  " + line for line in dark_hc],
        "  }",
        "}",
        "/* @end generated */",
    ]
    surface = lambda lines: re.search(r"--md-sys-color-surface: (#[0-9a-f]{6})", "\n".join(lines)).group(1)
    return "\n".join(out), {"light": surface(light), "dark": surface(dark)}


def main() -> int:
    check = "--check" in sys.argv
    text, surfaces = generated()
    tokens = TOKENS.read_text()
    new_tokens = re.sub(
        r"/\* @generated by scripts/make-tokens\.py.*?/\* @end generated \*/",
        lambda _: text,
        tokens,
        flags=re.S,
    )
    index = INDEX.read_text()
    new_index = re.sub(
        r'(<meta name="theme-color" content=")#[0-9a-f]{6}(" media="\(prefers-color-scheme: (light|dark)\)">)',
        lambda m: m.group(1) + surfaces[m.group(3)] + m.group(2),
        index,
    )
    manifest = json.loads(MANIFEST.read_text())
    manifest["theme_color"] = surfaces["light"]
    manifest["background_color"] = surfaces["light"]
    new_manifest = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"

    stale = [
        path.name
        for path, old, new in (
            (TOKENS, tokens, new_tokens),
            (INDEX, index, new_index),
            (MANIFEST, MANIFEST.read_text(), new_manifest),
        )
        if old != new
    ]
    if check:
        if stale:
            print("过期：" + "、".join(stale) + "；运行 python3 scripts/make-tokens.py")
            return 1
        print("配色令牌与种子一致。")
        return 0
    TOKENS.write_text(new_tokens)
    INDEX.write_text(new_index)
    MANIFEST.write_text(new_manifest)
    print("已写入：" + ("、".join(stale) if stale else "无变化"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
