#!/usr/bin/env python3
"""生成控制台的配色令牌：`res/console/tokens.css` 里 @generated 之间的那一段。

颜色不手调。种子色经 Material Color Utilities 的 HCT 算法（2025 版规范，
Tonal Spot 变体）推出全部系统角色，浅色、深色各一套，另各加一套「提高对比度」
（contrast_level 0.5，供 `prefers-contrast: more`，即 Apple 的「增强对比度」
与 Windows 的对比度主题之外的浏览器偏好）。

M3 只有 error 一种语义色；日志与连接状态还要「成功」「警告」。这两支按 M3 的
自定义色做法：先向种子色相做 harmonize，再用同一套 Tonal Spot 规则取
primary / on-primary / primary-container / on-primary-container 四个角色，
于是它们与主色在明度结构上完全同构，对比度也由算法保证。

同一次运行还把 theme-color 同步写进 index.html 与 manifest，避免两处漂移。

依赖：pip install materialyoucolor
运行：python3 scripts/make-tokens.py [--check]
"""

import json
import re
import sys
from pathlib import Path

from materialyoucolor.blend import Blend
from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors as M
from materialyoucolor.hct.hct import Hct
from materialyoucolor.scheme.scheme_tonal_spot import SchemeTonalSpot

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "res/console/tokens.css"
INDEX = ROOT / "res/console/index.html"
MANIFEST = ROOT / "res/console/manifest.webmanifest"

# 种子：靛青。知微是「看见细处」，取书写与夜读的颜色，而不是告警式的高饱和蓝。
SEED = 0xFF3F51B5
# 自定义语义色的原始色相，harmonize 之后才用。
SUCCESS = 0xFF2E8B57
WARNING = 0xFFB8860B

ROLES = [
    "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
    "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
    "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
    "error", "onError", "errorContainer", "onErrorContainer",
    "surface", "surfaceDim", "surfaceBright",
    "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
    "surfaceContainerHigh", "surfaceContainerHighest",
    "onSurface", "onSurfaceVariant", "outline", "outlineVariant",
    "inverseSurface", "inverseOnSurface", "inversePrimary",
    "scrim", "shadow",
]


def kebab(name: str) -> str:
    return re.sub(r"([A-Z])", lambda m: "-" + m.group(1).lower(), name)


def hexs(argb: int) -> str:
    return "#%06x" % (argb & 0xFFFFFF)


def scheme(source: int, dark: bool, contrast: float):
    return SchemeTonalSpot(Hct.from_int(source), dark, contrast, spec_version="2025")


def block(dark: bool, contrast: float) -> list[str]:
    base = scheme(SEED, dark, contrast)
    lines = [f"  --md-sys-color-{kebab(role)}: {hexs(getattr(M, role).get_argb(base))};" for role in ROLES]
    for name, raw in (("success", SUCCESS), ("warning", WARNING)):
        custom = scheme(Blend.harmonize(raw, SEED), dark, contrast)
        for role, suffix in (
            ("primary", ""),
            ("onPrimary", "on-"),
            ("primaryContainer", "container"),
            ("onPrimaryContainer", "on-container"),
        ):
            key = {"": name, "on-": f"on-{name}", "container": f"{name}-container",
                   "on-container": f"on-{name}-container"}[suffix]
            lines.append(f"  --md-sys-color-{key}: {hexs(getattr(M, role).get_argb(custom))};")
    return lines


def generated() -> tuple[str, dict]:
    light, dark = block(False, 0.0), block(True, 0.0)
    light_hc, dark_hc = block(False, 0.5), block(True, 0.5)
    out = [
        "/* @generated by scripts/make-tokens.py — 不要手改这一段 */",
        f"/* seed {hexs(SEED)} · Tonal Spot · spec 2025 */",
        ":root {",
        "  color-scheme: light;",
        *light,
        "}",
        "@media (prefers-color-scheme: dark) {",
        "  :root {",
        "    color-scheme: dark;",
        *["  " + line for line in dark],
        "  }",
        "}",
        "@media (prefers-contrast: more) {",
        "  :root {",
        *["  " + line for line in light_hc],
        "  }",
        "}",
        "@media (prefers-contrast: more) and (prefers-color-scheme: dark) {",
        "  :root {",
        *["  " + line for line in dark_hc],
        "  }",
        "}",
        "/* @end generated */",
    ]
    surface = lambda lines: re.search(r"--md-sys-color-surface: (#[0-9a-f]{6})", "\n".join(lines)).group(1)
    return "\n".join(out), {"light": surface(light), "dark": surface(dark)}


def card_tokens(tokens: str) -> str:
    # 同一语义角色、字阶和形状；卡片根字号 20px 补偿群聊缩略图，非第二套字阶。
    shared = tokens.split("/* @end generated */", 1)[1]
    out = ["/* @generated by scripts/make-tokens.py — shared M3E tokens */", shared]
    light = block(False, 0.0)
    for selector, dark in (("body.scheme-manual", False), ("body.scheme-control", False),
                           ("body.scheme-reply", False), ("body.scheme-news", False), ("body.dark", True)):
        out += [selector + " {", *block(dark, 0.0),
                "  --md-sys-color-on-surface-faint: var(--md-sys-color-on-surface-variant);",
                "  --md-sys-color-on-inverse-surface: var(--md-sys-color-inverse-on-surface);", "}"]
    out += [":root {", *light, "  font-size: 20px;",
            "  --md-font-plain: var(--md-ref-typeface-plain);", "  --md-font-mono: var(--md-ref-typeface-mono);"]
    for category in ("display", "headline", "title", "body", "label"):
        for size in ("large", "medium", "small"):
            name = category + "-" + size
            for short, full in (("size", "size"), ("line", "line-height")):
                out.append(f"  --md-type-{name}-{short}: var(--md-sys-typescale-{name}-{full});")
            weight = "display" if category in ("display", "headline") else "medium" if category in ("title", "label") else "regular"
            out += [f"  --md-type-{name}-weight: var(--md-sys-typescale-weight-{weight});",
                    f"  --md-type-{name}-track: var(--md-sys-typescale-tracking-label);"]
    for short, full in (("none", "none"), ("xs", "extra-small"), ("s", "small"), ("m", "medium"), ("l", "large"), ("l-plus", "large-increased"), ("xl", "extra-large"), ("2xl", "extra-extra-large"), ("full", "full")):
        out.append(f"  --md-shape-{short}: var(--md-sys-shape-corner-{full});")
    for i in range(1, 10):
        out.append(f"  --md-space-{i}: {i * 4}px;")
    for i in range(4):
        out.append(f"  --md-elevation-{i}: var(--md-sys-elevation-level{0 if i < 2 else i});")
    out += ["  --md-corner-notched: var(--md-shape-l) var(--md-shape-l) var(--md-shape-l) var(--md-shape-xs);",
            "  --md-corner-notched-end: var(--md-shape-l) var(--md-shape-l) var(--md-shape-xs) var(--md-shape-l);"]
    for suffix, percent in (("tint", 7), ("tint-strong", 15), ("line", 34)):
        out.append(f"  --md-sys-color-primary-{suffix}: color-mix(in srgb, var(--md-sys-color-primary) {percent}%, transparent);")
    out += ["}"]
    return "\n".join(out) + "\n"


def native_tokens() -> str:
    values = dict(re.findall(r"--md-sys-color-([a-z-]+): (#[0-9a-f]+);", "\n".join(block(False, 0.0))))
    out = ["// @generated by scripts/make-tokens.py; shared M3E light scheme.", "#![allow(dead_code)]", "use plotters::style::RGBColor;"]
    for name, value in values.items():
        key = name.upper().replace("-", "_")
        rgb = [int(value[i:i+2], 16) for i in (1,3,5)]
        out += [f'pub const {key}_HEX: &str = "{value}";', f'pub const {key}: RGBColor = RGBColor({rgb[0]}, {rgb[1]}, {rgb[2]});']
    out += ["pub const HUES: [RGBColor; 5] = [PRIMARY, SECONDARY, TERTIARY, SUCCESS, WARNING];",
            "pub const WORD_COLORS: [&str; 5] = [", "    PRIMARY_HEX,", "    SECONDARY_HEX,", "    TERTIARY_HEX,", "    SUCCESS_HEX,", "    WARNING_HEX,", "];"]
    return "\n".join(out) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    text, surfaces = generated()
    tokens = TOKENS.read_text()
    new_tokens = re.sub(
        r"/\* @generated by scripts/make-tokens\.py.*?/\* @end generated \*/",
        lambda _: text,
        tokens,
        flags=re.S,
    )
    index = INDEX.read_text()
    new_index = re.sub(
        r'(<meta name="theme-color" content=")#[0-9a-f]{6}(" media="\(prefers-color-scheme: (light|dark)\)">)',
        lambda m: m.group(1) + surfaces[m.group(3)] + m.group(2),
        index,
    )
    manifest = json.loads(MANIFEST.read_text())
    manifest["theme_color"] = surfaces["light"]
    manifest["background_color"] = surfaces["light"]
    new_manifest = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"

    cards = ROOT / "res/cards/tokens.css"
    native = ROOT / "src/render/tokens.rs"
    generated_files = [(cards, card_tokens(new_tokens)), (native, native_tokens())]
    stale = [
        path.name
        for path, old, new in (
            (TOKENS, tokens, new_tokens),
            (INDEX, index, new_index),
            (MANIFEST, MANIFEST.read_text(), new_manifest),
        )
        if old != new
    ]
    stale += [str(path.relative_to(ROOT)) for path, new in generated_files if not path.exists() or path.read_text() != new]
    if check:
        if stale:
            print("过期：" + "、".join(stale) + "；运行 python3 scripts/make-tokens.py")
            return 1
        print("配色令牌与种子一致。")
        return 0
    for path, new in generated_files:
        path.write_text(new)
    TOKENS.write_text(new_tokens)
    INDEX.write_text(new_index)
    MANIFEST.write_text(new_manifest)
    print("已写入：" + ("、".join(stale) if stale else "无变化"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
